import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { theme } from '../../tailwind.config'

const Home: NextPage = () => {
  return (
    <div className="h-screen w-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-[25px] text-red-900 underline">
        Welcome to <a href="https://nextjs.org">Next.js!</a>
      </h1>
    </div>
  )
}

export default Home
